name: Create json index
on:
  push:
    branches: 
    - main

jobs:
  reindex-json-file:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository
      contents: write

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y libzzip-dev
        sudo apt-get install -y git-lfs
        git lfs install
        
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }} 
        lfs: 'true'

    - uses: leafo/gh-actions-lua@v10

    - uses: leafo/gh-actions-luarocks@v4

    - name: Install luarocks modules
      run: |
        luarocks install json-lua
        luarocks install luazip

    - name: Run indexing
      run: |
        lua reindex.lua

    # Commit all changed files back to the repository
    - uses: stefanzweifel/git-auto-commit-action@v5        
      with:
        commit_message: Automated package index update.
        file_pattern: 'packages/*.packages.json'
