name: Validate mpackage file

on: pull_request

jobs:
  check-zip-contents:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master
      
    - name: Unzip the file and check it out
      id: validate-mpackage-file
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        FILE=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path')
        echo $FILE
        
        # check only 1 file has been uploaded per PR
        if [ `echo "$FILE" |wc -l`  -gt 1 ]; then
          echo "Error: Only one package file per pull request please."
          exit(1)
        else
          echo "Pass: just one file uploaded."
        fi

        # unzip the mpackage
        unzip -o $FILE -d unzipped_contents
        ls -al unzipped_package

        #only valid if it has a config.lua
        if [ -f "unzipped_package/config.lua" ]; then
          echo "Pass: config.lua is present"
        else
          echo "Error: config.lua is missing."
          exit 1
        fi

        #grep for some vital details
        if grep -q "mpackage =" unzipped_contents/config.lua; then
          echo "Pass: has a valid mpackage name"
        else
          echo "Error: not a valid mpackage file"
          exit(1)
        fi
        
        if grep -q "version =" unzipped_contents/config.lua; then
          echo "Pass: config.lua contains a version number"
        else
          echo "Error: does not contain a version number"
          exit(1)          
        fi   

        if grep -q "mpackage =" unzipped_contents/config.lua; then
          echo "Pass: has a valid mpackage name"
        else
          echo "Error: not a valid mpackage file"
          exit(1)            
        fi        

        if grep -q "author =" unzipped_contents/config.lua; then         
          echo "Pass: has a valid author name"
        else
          echo "Error: does not contain a valid author name"
          exit(1)          
        fi  

        if grep -q "description =" unzipped_contents/config.lua; then
          echo "Pass: has a valid description"      
        else
          echo "Error: does not contain a valid description"
          exit(1)             
        fi
