name: Validate mpackage file

on: pull_request

jobs:
  check-zip-contents:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install unzip
      run: sudo apt-get install -y unzip

    - name: List files in the pull request
      id: list-files
      run: |
        echo "File changed in this PR:"
        FILE=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path')
        echo $FILES
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Fetch contents of changed files
      id: fetch_contents
    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      run: |
        echo "Fetching contents of $file"
        curl -s -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3.raw" \
            -o "$(basename "$FILE")" \
               "https://api.github.com/repos/${{ github.repository }}/contents/$FILE?ref=${{ github.event.pull_request.head.sha }}"
        ls -al .
    - name: Unzip archive
      run: unzip -o $FILE -d unzipped_contents

    - name: List contents of the ZIP file
      run: ls -R unzipped_contents

    - name: Check for specific file
      run: |
        if [ -f "unzipped_contents/config.lua" ]; then
          echo "config.lua is present."
        else
          echo "Error: config.lua is missing."
          exit 1
        fi
