name: Validate mpackage file

on: pull_request

jobs:
  check-zip-contents:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install unzip
      run: sudo apt-get install -y unzip

    - name: Unzip archive
      run: unzip -o archive.zip -d unzipped_contents

    - name: List contents of the ZIP file
      run: ls -R unzipped_contents

    - name: Check for specific file
      run: |
        if [ -f "unzipped_contents/config.lua" ]; then
          echo "config.lua is present."
        else
          echo "Error: config.lua is missing."
          exit 1
        fi
