name: Validate mpackage file

on: pull_request

jobs:
  check-zip-contents:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master
      
    - name: List files in the pull request
      id: list-files
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        FILE=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path')
        echo $FILE
        unzip -o $FILE -d unzipped_contents
        ls -al

    - name: Fetch contents of changed files
      id: fetch-contents
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      run: |
        echo "Fetching contents of $FILE"
        echo "Repo is: ${{ github.repository }}"
        echo "SHA is : ${{ github.event.pull_request.head.sha }}"
        ls -al .
      #  curl -s -H "Authorization: Bearer $GH_TOKEN" \
      #      -H "Accept: application/vnd.github.v3.raw" \
      #      -o "$(basename $FILE)" \
      #      "https://api.github.com/repos/${{ github.repository }}/contents/$FILE?ref=${{ github.event.pull_request.head.sha }}"

    - name: List contents of the ZIP file
      run: ls -R unzipped_contents

    - name: Check for specific file
      run: |
        if [ -f "unzipped_contents/config.lua" ]; then
          echo "config.lua is present."
        else
          echo "Error: config.lua is missing."
          exit 1
        fi
